// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZGn8W_cBNa7g6QXzsCOISSuIALoi8sk',
    appId: '1:507173254241:web:c1b2e54ed4a7019278a620',
    messagingSenderId: '507173254241',
    projectId: 'crudopeartion-81e6c',
    authDomain: 'crudopeartion-81e6c.firebaseapp.com',
    databaseURL: 'https://crudopeartion-81e6c-default-rtdb.firebaseio.com',
    storageBucket: 'crudopeartion-81e6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdtRrQHdStCF2iS4IZ6s-Jei5bDoJpR8',
    appId: '1:507173254241:android:29bb141329dad9e478a620',
    messagingSenderId: '507173254241',
    projectId: 'crudopeartion-81e6c',
    databaseURL: 'https://crudopeartion-81e6c-default-rtdb.firebaseio.com',
    storageBucket: 'crudopeartion-81e6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDVq2qCLIQeN__TSfIbNwjux0_blQInn8',
    appId: '1:507173254241:ios:a011430b56e0bb7d78a620',
    messagingSenderId: '507173254241',
    projectId: 'crudopeartion-81e6c',
    databaseURL: 'https://crudopeartion-81e6c-default-rtdb.firebaseio.com',
    storageBucket: 'crudopeartion-81e6c.firebasestorage.app',
    iosBundleId: 'com.example.crudoperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDVq2qCLIQeN__TSfIbNwjux0_blQInn8',
    appId: '1:507173254241:ios:a011430b56e0bb7d78a620',
    messagingSenderId: '507173254241',
    projectId: 'crudopeartion-81e6c',
    databaseURL: 'https://crudopeartion-81e6c-default-rtdb.firebaseio.com',
    storageBucket: 'crudopeartion-81e6c.firebasestorage.app',
    iosBundleId: 'com.example.crudoperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpZGn8W_cBNa7g6QXzsCOISSuIALoi8sk',
    appId: '1:507173254241:web:9d57606f8540f83f78a620',
    messagingSenderId: '507173254241',
    projectId: 'crudopeartion-81e6c',
    authDomain: 'crudopeartion-81e6c.firebaseapp.com',
    databaseURL: 'https://crudopeartion-81e6c-default-rtdb.firebaseio.com',
    storageBucket: 'crudopeartion-81e6c.firebasestorage.app',
  );
}
